### ISSUE TITLE
Set report to config

### ISSUE THREAD

**Issue by tardinha** [nswdpc/silverstripe-csp#13]
Update doco, need to add report to config in project, e.g.;

```
---
Name: app-csp-config
After:
  - '#csp_configuration'
---
NSWDPC\Utilities\ContentSecurityPolicy\Policy:
  include_report_to: true
```

**Comment by JamesDPC** [comment]
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=1098885

There were some workarounds needed to support Chromium and Firefox's varying levels of support for report-to and report-uri. Enabling report-to in Chromiums caused reports to not be sent, even if report-uri was added. Firefox didn't support report-to... only report-uri and ignored report-to.

There's been a bit of water under the bridge since the browser versions mentioned,  so would be best to test in the latest Chromiums & Firefox to see if report-to alongside report-uri works.

Provided the browsers play along with both, the change here would be to drop the  "include_report_to" config setting completely and allow report-to to be set regardless.

Related: when selecting a Minimum CSP Level of 3, the report-uri directive is dropped as it's a deprecated to option.

**Comment by JamesDPC** [comment]
There is a change here: https://github.com/nswdpc/silverstripe-csp/compare/master...feat-reporting-endpoints to improve reporting using the Reporting API.

The handling of the report-to (Reporting API) directive is pretty opaque in chromium, when it is present along with a Report-To header, no reporting takes place. Firefox doesn't support report-to at all. Both support the original but deprecated report-uri directive.
Based on some readings, there is now a Reporting-Endpoints header and chromium supports that based on some testing. The report-to directive refers to an endpoint named in the Reporting-Endpoints header.

```
Content-Security-Policy: ....;report-uri https://example.com/report-uri-csp;report-to csp-endpoint;
Reporting-Endpoints: csp-endpoint="https://example.com/reporting-api-endpoint"
```

NEL has been split off from CSP reporting. It only supports the Report-To header, not Reporting-Endpoints.

Based on those changes, another field has been added to handle services that have differing Reporting API & report-uri directives.

**Comment by JamesDPC** [comment]
Completed in #14 (v0.4.3)
